# GitHub Pages 配置文件
title: 我的每日计划系统
description: 一个基于 GitHub Pages 的个人每日计划管理系统
author: 您的姓名
url: https://您的用户名.github.io
baseurl: /DailyPlan

# 主题设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 包含文件
include:
  - _pages

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
